name: aiper
description: "AI-Powered Crisis Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  google_maps_flutter: ^2.5.3

  # AI & Others
  google_generative_ai: ^0.4.7
  mqtt_client: ^10.3.0
  audioplayers: ^5.2.1
  vibration: ^2.0.0

  # Map Packages (correct stable versions)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # UI / Helpers
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  geolocator: ^13.0.0
  package_info_plus: ^9.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/sirens.gif
    - assets/sounds/sirens.mp3
